# Dockerfile.dev
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install system dependencies (good for psycopg2, mysqlclient, etc.)
RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc libmariadb-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Python deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Run server with hot reload
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
