# Generated by Django 4.2.7 on 2024-04-13 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tunis', '0012_rename_elvstunis0_elvstunis11'),
    ]

    operations = [
        migrations.AddField(
            model_name='elvstunis',
            name='dre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tunis.dretunis'),
        ),
    ]
