# Generated by Django 4.2.7 on 2024-06-26 03:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0032_alter_del1_dre'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminecoledata',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adminecoledata',
            name='numero',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be 8 digits', regex='^\\d{8}$')]),
        ),
    ]
